In [1]:
import requests

In [3]:
url="https://api.exchangerate.host/live"

In [4]:
params={"access_key":"d90db47f7e915004f6aa426149e209ea"}

In [5]:
response=requests.get(url,params=params)

In [6]:
print(response.status_code)

401

In [7]:
print(response.json())

{'success': False, 'error': {'code': 101, 'type': 'invalid_access_key', 'info': 'You have not supplied a valid API Access Key. [Technical Support: support@apilayer.com]'}}

In [8]:
import requests

url = "https://api.exchangerate.host/live"

params = {
    "access_key": "d90db47f7e915004f6aa426149e209ea"
}

response = requests.get(url, params=params)

print(response.status_code)
print(response.json())

401
{'success': False, 'error': {'code': 101, 'type': 'invalid_access_key', 'info': 'You have not supplied a valid API Access Key. [Technical Support: support@apilayer.com]'}}

In [9]:
import requests
import pandas as pd

url = "https://dummyjson.com/products"

response = requests.get(url)

print(response.status_code)

df = pd.DataFrame(response.json()["products"])

print(df.head())

200
   id                          title  \
0   1  Essence Mascara Lash Princess
1   2  Eyeshadow Palette with Mirror
2   3                Powder Canister
3   4                   Red Lipstick
4   5                Red Nail Polish

                                         description category  price  \
0  The Essence Mascara Lash Princess is a popular...   beauty   9.99
1  The Eyeshadow Palette with Mirror offers a ver...   beauty  19.99
2  The Powder Canister is a finely milled setting...   beauty  14.99
3  The Red Lipstick is a classic and bold choice ...   beauty  12.99
4  The Red Nail Polish offers a rich and glossy r...   beauty   8.99

   discountPercentage  rating  stock                   tags           brand  \
0               10.48    2.56     99      [beauty, mascara]         Essence
1               18.19    2.86     34    [beauty, eyeshadow]  Glamour Beauty
2                9.84    4.64     89  [beauty, face powder]    Velvet Touch
3               12.16    4.36     91     [beauty, lipstick]  Chic Cosmetics
4               11.44    4.32     79  [beauty, nail polish]    Nail Couture

   ...                                         dimensions  \
0  ...  {'width': 15.14, 'height': 13.08, 'depth': 22.99}
1  ...   {'width': 9.26, 'height': 22.47, 'depth': 27.67}
2  ...  {'width': 29.27, 'height': 27.93, 'depth': 20.59}
3  ...  {'width': 18.11, 'height': 28.38, 'depth': 22.17}
4  ...  {'width': 21.63, 'height': 16.48, 'depth': 29.84}

   warrantyInformation         shippingInformation availabilityStatus  \
0      1 week warranty  Ships in 3-5 business days           In Stock
1      1 year warranty            Ships in 2 weeks           In Stock
2    3 months warranty  Ships in 1-2 business days           In Stock
3      3 year warranty             Ships in 1 week           In Stock
4     1 month warranty             Ships overnight           In Stock

                                             reviews          returnPolicy  \
0  [{'rating': 3, 'comment': 'Would not recommend...      No return policy
1  [{'rating': 5, 'comment': 'Great product!', 'd...  7 days return policy
2  [{'rating': 4, 'comment': 'Would buy again!', ...      No return policy
3  [{'rating': 4, 'comment': 'Great product!', 'd...  7 days return policy
4  [{'rating': 2, 'comment': 'Poor quality!', 'da...      No return policy

  minimumOrderQuantity                                               meta  \
0                   48  {'createdAt': '2025-04-30T09:41:02.053Z', 'upd...
1                   20  {'createdAt': '2025-04-30T09:41:02.053Z', 'upd...
2                   22  {'createdAt': '2025-04-30T09:41:02.053Z', 'upd...
3                   40  {'createdAt': '2025-04-30T09:41:02.053Z', 'upd...
4                   22  {'createdAt': '2025-04-30T09:41:02.053Z', 'upd...

                                              images  \
0  [https://cdn.dummyjson.com/product-images/beau...
1  [https://cdn.dummyjson.com/product-images/beau...
2  [https://cdn.dummyjson.com/product-images/beau...
3  [https://cdn.dummyjson.com/product-images/beau...
4  [https://cdn.dummyjson.com/product-images/beau...

                                           thumbnail
0  https://cdn.dummyjson.com/product-images/beaut...
1  https://cdn.dummyjson.com/product-images/beaut...
2  https://cdn.dummyjson.com/product-images/beaut...
3  https://cdn.dummyjson.com/product-images/beaut...
4  https://cdn.dummyjson.com/product-images/beaut...

[5 rows x 22 columns]

In [10]:
df = pd.DataFrame(response.json()["products"])[
    ['id', 'title', 'price', 'category', 'rating']
]

df.head()

   id                          title  price category  rating
0   1  Essence Mascara Lash Princess   9.99   beauty    2.56
1   2  Eyeshadow Palette with Mirror  19.99   beauty    2.86
2   3                Powder Canister  14.99   beauty    4.64
3   4                   Red Lipstick  12.99   beauty    4.36
4   5                Red Nail Polish   8.99   beauty    4.32

In [11]:
print(df.head(20))

    id                                      title    price    category  rating
0    1              Essence Mascara Lash Princess     9.99      beauty    2.56
1    2              Eyeshadow Palette with Mirror    19.99      beauty    2.86
2    3                            Powder Canister    14.99      beauty    4.64
3    4                               Red Lipstick    12.99      beauty    4.36
4    5                            Red Nail Polish     8.99      beauty    4.32
5    6                        Calvin Klein CK One    49.99  fragrances    4.37
6    7                    Chanel Coco Noir Eau De   129.99  fragrances    4.26
7    8                               Dior J'adore    89.99  fragrances    3.80
8    9                         Dolce Shine Eau de    69.99  fragrances    3.96
9   10                         Gucci Bloom Eau de    79.99  fragrances    2.74
10  11                       Annibale Colombo Bed  1899.99   furniture    4.77
11  12                      Annibale Colombo Sofa  2499.99   furniture    3.92
12  13               Bedside Table African Cherry   299.99   furniture    2.87
13  14  Knoll Saarinen Executive Conference Chair   499.99   furniture    4.88
14  15           Wooden Bathroom Sink With Mirror   799.99   furniture    3.59
15  16                                      Apple     1.99   groceries    4.19
16  17                                 Beef Steak    12.99   groceries    4.47
17  18                                   Cat Food     8.99   groceries    3.13
18  19                               Chicken Meat     9.99   groceries    3.19
19  20                                Cooking Oil     4.99   groceries    4.80

In [12]:
df=pd.DataFrame()

In [13]:
df

Empty DataFrame
Columns: []
Index: []

In [16]:
import requests
import pandas as pd

df = pd.DataFrame()

for i in range(0, 100, 10):
    response = requests.get(
        
        f"https://dummyjson.com/products?limit=10&skip={i}"
    )

    temp_df = pd.DataFrame(response.json()["products"])[
        ['id', 'title', 'price', 'category', 'rating']
    ]

    df = pd.concat([df, temp_df], ignore_index=True)

df.head()

   id                          title  price category  rating
0   1  Essence Mascara Lash Princess   9.99   beauty    2.56
1   2  Eyeshadow Palette with Mirror  19.99   beauty    2.86
2   3                Powder Canister  14.99   beauty    4.64
3   4                   Red Lipstick  12.99   beauty    4.36
4   5                Red Nail Polish   8.99   beauty    4.32

In [17]:
df.to_csv('Movies.csv')