# 🔹 What is Categorical Data?

In a dataset, some columns contain **categories/words instead of numbers**.

For example:

* `Name` → categorical
* `Gender` → categorical
* `City` → categorical
* `Purchased` → categorical

So we need to convert:

**Words → Numbers**

This process is called **Encoding**.


# 🔥 Main Types of Encoding

You should mainly know these:

1. **Label Encoding**
2. **Ordinal Encoding**
3. **One-Hot Encoding**
4. **Dummy Encoding** — basically one-hot encoding with one column removed
5. **Target Encoding** — more advanced

For beginner ML, focus heavily on **Label Encoding and One-Hot Encoding**.

---

# 1️⃣ Label Encoding

Label Encoding converts each category into a number.

Example:
Male
Female
Male
Female
```

After encoding:

```text
Male   → 0
Female → 1
```

# 2️⃣ Ordinal Encoding

Ordinal encoding is useful when categories have a **natural order**.

For example:
School
Bachelor
Master
PhD
```

There is an order:

```text
School < Bachelor < Master < PhD
```

So we can encode:

```text
School   → 0
Bachelor → 1
Master   → 2
PhD      → 3
```

Here, numbers actually represent the order.

# 3️⃣ One-Hot Encoding ⭐⭐⭐
Suppose we have a column called **Color**:

| Color |
| ----- |
| Red   |
| Blue  |
| Green |
| Red   |

A Machine Learning model cannot directly understand `"Red"`, `"Blue"`, `"Green"`.

So we convert them into **0 and 1**.

### Step 1: Create separate columns

Red
Blue
Green
```

### Step 2: Put 1 for the matching color, otherwise 0

| Color | Red | Blue | Green |
| ----- | --: | ---: | ----: |
| Red   |   1 |    0 |     0 |
| Blue  |   0 |    1 |     0 |
| Green |   0 |    0 |     1 |
| Red   |   1 |    0 |     0 |

That's **One-Hot Encoding**. 🎯

# 4️⃣ Dummy Encoding
Let's use the same example:

| Color |
| ----- |
| Red   |
| Blue  |
| Green |
| Red   |

### One-Hot Encoding

We would create **3 columns**:

| Color | Red | Blue | Green |
| ----- | --: | ---: | ----: |
| Red   |   1 |    0 |     0 |
| Blue  |   0 |    1 |     0 |
| Green |   0 |    0 |     1 |
| Red   |   1 |    0 |     0 |

---

## Dummy Encoding

In **dummy encoding, we remove one column**.

For example, remove `Green`:

| Color | Red | Blue |
| ----- | --: | ---: |
| Red   |   1 |    0 |
| Blue  |   0 |    1 |
| Green |   0 |    0 |
| Red   |   1 |    0 |

### 🧠 Why does Green become `0, 0`?

Because:
Red = 0
Blue = 0
```

So we know it must be:
Green
```

Therefore, we don't need a separate Green column.

# 5️⃣ Target Encoding

> **Replace each category with the average value of the target for that category.**

### Example

Suppose we want to predict **whether a student passes**.

| City   | Passed |
| ------ | -----: |
| Delhi  |      1 |
| Delhi  |      0 |
| Mumbai |      1 |
| Mumbai |      1 |
| Delhi  |      1 |

Here:

* **City** = categorical feature
* **Passed** = target

---

### Step 1: Find the average target for each city

#### Delhi

Delhi students:

```text
1, 0, 1
```

Average:

```text
(1 + 0 + 1) / 3 = 0.67
```

So:

**Delhi → 0.67**

#### Mumbai

Mumbai students:

```text
1, 1
```

Average:

```text
(1 + 1) / 2 = 1.00
```

So:

**Mumbai → 1.00**

---

### Step 2: Replace the city with its average

Original:

| City   | Passed |
| ------ | -----: |
| Delhi  |      1 |
| Delhi  |      0 |
| Mumbai |      1 |
| Mumbai |      1 |
| Delhi  |      1 |

After target encoding:

| City   | Encoded City | Passed |
| ------ | -----------: | -----: |
| Delhi  |         0.67 |      1 |
| Delhi  |         0.67 |      0 |
| Mumbai |         1.00 |      1 |
| Mumbai |         1.00 |      1 |
| Delhi  |         0.67 |      1 |

So:

```text
Delhi  → 0.67
Mumbai → 1.00
```

### 🧠 Super easy way to remember

**Target Encoding = Category → Average Target**

```text
Delhi  → average Pass value → 0.67
Mumbai → average Pass value → 1.00
```

### ⚠️ Important

Target encoding needs care because the target values are being used to create the feature. If done incorrectly, it can cause **data leakage**. In real ML projects, calculate the encodings using the training data appropriately rather than using the entire dataset before splitting.

**One-line definition:**

> Target encoding replaces each categorical value with a statistic (usually the mean) of the target variable for that category.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('customer.csv')

In [ ]:
df.sample(5)

    age  gender   review education purchased
37   94    Male  Average        PG       Yes
0    30  Female  Average    School        No
21   32    Male  Average        PG        No
19   97    Male     Poor        PG       Yes
18   19    Male     Good    School        No

In [ ]:
df=df.iloc[:,2:]

In [ ]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)
# Take all rows from the last column.->[:,-1]

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
#Ordinal Encoding converts categories into numbers when the categories have a meaningful order.

In [ ]:
x_train

     review education
18     Good    School
5   Average    School
8   Average        UG
32  Average        UG
14     Poor        PG
6      Good    School
25     Good    School
21  Average        PG
11     Good        UG
9      Good        UG
39     Poor        PG
49     Good        UG
12     Poor    School
29  Average        UG
28     Poor    School
2      Good        PG
45     Poor        PG
19     Poor        PG
1      Poor        UG
41     Good        PG
35     Poor    School
44  Average        UG
43     Poor        PG
46     Poor        PG
7      Poor    School
22     Poor        PG
26     Poor        PG
3      Good        PG
40     Good    School
36     Good        UG
34  Average    School
15     Poor        UG
33     Good        PG
47     Good        PG
27     Poor        PG
48     Good        UG
30  Average        UG
23     Good    School
31     Poor    School
4   Average        UG

In [ ]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
#we have given poor less value then good

In [ ]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
x_train=oe.transform(x_train)
x_test=oe.transform(x_test)

In [ ]:
x_train

array([[2., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [1., 1.]])

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
x_train

array([[2., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [1., 1.]])

//USE SHOULD NOT USE LABEL ENCODER FOR INPUT COLUMN
//USED WHEN U WORK WITH OUTPUT COLUMN

| Encoder            | Common use                        | Example                                     |
| ------------------ | --------------------------------- | ------------------------------------------- |
| **LabelEncoder**   | Target `y`                        | Yes → 1, No → 0                             |
| **OrdinalEncoder** | Feature `X` with meaningful order | Poor → 0, Average → 1, Good → 2             |
| **OneHotEncoder**  | Feature `X` with no order         | Delhi, Mumbai, Bangalore → separate columns |

In [ ]:
from sklearn.preprocessing import LabelEncoder
#LabelEncoder is mainly used to convert categorical labels into numbers,
#especially when the categorical column is the target/output y of an ML model.

In [ ]:
le=LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_
#"Show me the categories that you learned, and the order in which you assigned them."

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [ ]:
y_train

array([0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0])

0 → No
1 → Yes